name: Build Quarkus

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-quarkus:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: jvm standard build
        run: |
          cd employee-quarkus
          mvn clean install
          docker build . -f src/main/docker/Dockerfile.jvm -t quarkus-employee-jvm:0.0.2-SNAPSHOT
      
      - name: multi stage from scratch build
        run: |
          cd employee-quarkus
          docker build . -f src/main/docker/Dockerfile.scratch.native -t quarkus-employee-native:0.0.2-SNAPSHOT-scratch

      # https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-github-packages
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: push to docker
        run: |
          docker push quarkus-employee-native:0.0.2-SNAPSHOT-scratch


      # - uses: DeLaGuardo/setup-graalvm@4.0
      #   with:
      #     # GraalVM version, no pattern syntax available atm
      #     graalvm: '21.0.0.2'
      #     # Java version, optional, defaults to 'java8'. Available options are 'java8' and 'java11'.
      #     java: 'java11'
      #     # Architecture flag, optional, defaults to 'amd64'. Available options are 'amd64' and 'aarch64'. Later is available only for linux runners.
      #     arch: 'amd64'
      # - run: java -version
      # - name: Install native-image component
      #   run: |
      #     gu install native-image
      
      # - name: Cache Maven packages
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.m2
      #     key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: ${{ runner.os }}-m2
      
      # - name: Build Native Image and Run Application
      #   run: |
      #     mvn clean package -DskipTests -Pspring-native,build-native-image
      #     ./target/com.example.demo.demoapplication &
      #     sleep 10

      # - name: Run FunctionalTests
      #   run: |
      #     mvn test -Pfunctional-test
