name: Build Spring Boot JVM

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-quarkus:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      
      # potential upgrade: https://docs.github.com/en/actions/guides/publishing-java-packages-with-maven#publishing-packages-to-github-packages
      - name: jvm standard build
        run: |
          cd employee-sb
          mvn clean install
          docker build . -f src/main/docker/Dockerfile -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:0.0.1-SNAPSHOT-SB-JVM

      # https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-github-packages
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: push to docker
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:0.0.1-SNAPSHOT-SB-JVM