name: Build Spring Boot Native

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-springboot-native:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      
      # # potential upgrade: https://docs.github.com/en/actions/guides/publishing-java-packages-with-maven#publishing-packages-to-github-packages
      # - name: multi stage from scratch build
      #   run: |
      #     cd sb-employee-native
      #     mvn clean install
      #     docker build . -f src/main/docker/Dockerfile -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:0.0.1-SNAPSHOT-SB-NATIVE

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      # - name: Cache Maven packages
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.m2
      #     key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: ${{ runner.os }}-m2

      - name: Build Docker Image
        run: |
          cd sb-employee-native
          mvn -e -X clean spring-boot:build-image -DskipTests -Pspring-native,build-docker-image
          echo 'listing docker images'
          docker image ls

      # # https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-github-packages
      # - name: Log in to the Container registry
      #   uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      
      # - name: push to docker
      #   run: |
      #     docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:0.0.1-SNAPSHOT-SB-NATIVE